/*
 * adc_handler.h
 *
 *  Created on: 26 wrz 2021
 *      Author: Marek Jaromin
 */

#ifndef INC_ADC_HANDLER_H_
#define INC_ADC_HANDLER_H_

#include <stdint.h>

#define CORRECT_TEMPERATURE 		1
#define INCORRECT_TEMPERATURE		0

#define VOLTAGE_RISE				0.01 	//STORES VALUE OF VOLTAGE THAT RISE WITH EVERY CELSIUS DEEGREE FOR LM35
#define ADC_REFERENCE_VOLTAGE 		3.3 	//STORES REFERENCE VOLTAGE VALUE OF ADC
#define ADC_RESOLUTION				4096	//STORES ADC RESOLUTION VALUE

#define MAX_THRESHOLD_TEMPERATURE	33		//STORES MAXIMUM THRESHOLD TEMPERATURE
#define MIN_THRESHOLD_TEMPERATURE	26		//STORES MINIMUM THRESHOLD TEMPERATURE

float CONV_ADC_VOLTAGE_TO_TEMPERATURE(uint16_t adc_read_value);

#endif /* INC_ADC_HANDLER_H_ */
